### ISSUE TITLE
sn_grs.c interface unused param with wrong description

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client-c#140]
In sn_grs.c the function sn_grs_list_resource(struct grs_s *handle, const char *path) does not use the path parameter. With one exception, a NULL pointer check that is in conflict with header prototype description:

` \param   *path   A pointer to an array containing the path or a NULL pointer.`
 
```
if( handle == NULL || path == NULL){
    return NULL;
}
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1781

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
