### ISSUE TITLE
Error in passing external memory block to application

### ISSUE THREAD

**Issue by ghseb** [ARMmbed/mbed-client-c#142]
When receiving a block-wise message that has the flag `external_memory_block` set `sn_nsdl_get_resource` fails because it requires a `char *` instead of a length delimeted `uint8_t *` in sn_nsdl.c. The result is that the block is not passed to the application.

```
#if SN_COAP_MAX_BLOCKWISE_PAYLOAD_SIZE
     // Pass block to application if external_memory_block is set
     if(coap_packet_ptr->coap_status == COAP_STATUS_PARSER_BLOCKWISE_MSG_RECEIVING) {
        resource = sn_nsdl_get_resource(handle, coap_packet_ptr->uri_path_ptr); // Returns Null because coap_packet_ptr->uri_path_ptr is not zero delimeted
         if(resource && resource->static_resource_parameters->external_memory_block) {
             sn_coap_protocol_block_remove(handle->grs->coap,
                                           src_ptr,
                                           coap_packet_ptr->payload_len,
                                           coap_packet_ptr->payload_ptr);
         } else {
             resource = NULL;
         }
     }
 #endif
```
I suggest using a zero delimeted copy of uri_path_pointer as parameter for sn_nsdl_get_resource.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1881

**Comment by ghseb** [comment]
Any news on this topic? As suggested it would be pretty easy to create a copy of the uri_path which is zero delimited.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
