### ISSUE TITLE
obs not compatible with Leshan

### ISSUE THREAD

**Issue by amq** [ARMmbed/mbed-client-c#143]
It is also mentioned directly in code:

```
            /* ;obs */
             // This needs to be re-visited and may be need an API for maganging obs value for different server implementation
#ifndef COAP_DISABLE_OBS_FEATURE
            if (resource_temp_ptr->observable) {
                *temp_ptr++ = ';';
                memcpy(temp_ptr, obs_parameter, OBS_PARAMETER_LEN);
                temp_ptr += OBS_PARAMETER_LEN;
            }
#endif
```

Changing `obs` to `obs=1` solves the problem.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2045

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
