### ISSUE TITLE
Enhanced 'alloc' and 'free' function

### ISSUE THREAD

**Issue by haosu1987** [ARMmbed/mbed-client-c#85]
The 'malloc' and 'free' are defined as follows:

```
struct nsdl_s {
    ...
    void *(*sn_nsdl_alloc)(uint16_t);
    void (*sn_nsdl_free)(void *);
    ...
};
```

But it can't fit the following function prototype:

```
    void *my_malloc(void *ctx, size_t size);
    void my_free(void *ctx, void *ptr);
```

Therefore, I suggest that the structure is defined as follows：

```
struct nsdl_s {
    ...
    void *sn_nsdl_mem_ctx;
    void *(*sn_nsdl_alloc)(void *, uint16_t);
    void (*sn_nsdl_free)(void *, void *);
    ...
};
```

After sn_nsdl_init, you can call the 'malloc' and 'free' with the wrapper as follows:

```
void *sn_nsdl_malloc(struct nsdl_s *ctx, size_t size)
{
    return (ctx && ctx->sn_nsdl_alloc) ? (ctx->sn_nsdl_alloc(ctx->sn_nsdl_mem_ctx, size)) : NULL;
}
void sn_nsdl_free(struct nsdl_s *ctx, void *ptr)
{
    if (ctx && ctx->sn_nsdl_free)
    {
        ctx->sn_nsdl_free(ctx->sn_nsdl_mem_ctx, ptr);
    }
}
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1063

**Comment by yogpan01** [comment]
Hi,
Thanks for suggestion . We will take a look into your proposal.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
